apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-init
  template:
    metadata:
      labels:
        app: web-init
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5
      initContainers:
      - name: busybox-init
        image: busybox
        command: ['sh', '-c', "until nslookup service-init.\
        $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)\
        .svc.cluster.local; do echo waiting for svc-nginx-init; sleep 2; done"]
