apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multitool-busybox
  namespace: netology-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-main
  template:
    metadata:
      labels:
        app: app-main
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "current date = $(date)" >> /busybox_data/date.log; sleep 5; done']
        volumeMounts:
          - name: app-vol-pvc
            mountPath: /busybox_data
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - name: app-vol-pvc
            mountPath: /multitool_data
      volumes:
        - name: app-vol-pvc
          persistentVolumeClaim:
            claimName: pvc1-vol
