apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-vol
  namespace: netology-2
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
