apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  namespace: netology-2
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>This is Netology Homework - The task №2</h1>
    </html>
