apiVersion: v1
kind: Service
metadata:
  name: deployment-service-nodeport
  namespace: netology
spec:
  ports:
    - name: http-app
      port:  80
      nodePort: 30000
    - name: http-app-multi
      port:  8080
      nodePort: 30001
  selector:
    app: main
  type: NodePort
